# Kyiv
MetroStation.create(district_id: 10, name_ru: "Академгородок", name_uk: "Академмістечко", name_en: "Akademmistechko", color: "red", sequence: 110)
MetroStation.create(district_id: 10, name_ru: "Житомирская", name_uk: "Житомирська", name_en: "Zhytomyrska", color: "red", sequence: 111)
MetroStation.create(district_id: 10, name_ru: "Святошин", name_uk: "Святошин", name_en: "Sviatoshyn", color: "red", sequence: 112)
MetroStation.create(district_id: 10, name_ru: "Нивки", name_uk: "Нивки", name_en: "Nyvky", color: "red", sequence: 113)
MetroStation.create(district_id: 10, name_ru: "Берестейская", name_uk: "Берестейська", name_en: "Beresteiska", color: "red", sequence: 114)
MetroStation.create(district_id: 10, name_ru: "Шулявская", name_uk: "Шулявська", name_en: "Shuliavska", color: "red", sequence: 115)
MetroStation.create(district_id: 10, name_ru: "Политехнический институт", name_uk: "Політехнічний інститут", name_en: "Politekhnichnyi Instytut", color: "red", sequence: 116)
MetroStation.create(district_id: 10, name_ru: "Вокзальная", name_uk: "Вокзальна", name_en: "Vokzalna", color: "red", sequence: 117)
MetroStation.create(district_id: 10, name_ru: "Университет", name_uk: "Університет", name_en: "Universytet", color: "red", sequence: 118)
MetroStation.create(district_id: 10, name_ru: "Театральная", name_uk: "Театральна", name_en: "Teatralna", color: "red", sequence: 119)
MetroStation.create(district_id: 10, name_ru: "Крещатик", name_uk: "Хрещатик", name_en: "Khreschatyk", color: "red", sequence: 120)
MetroStation.create(district_id: 10, name_ru: "Арсенальная", name_uk: "Арсенальна", name_en: "Arsenalna", color: "red", sequence: 121)
MetroStation.create(district_id: 10, name_ru: "Днепр", name_uk: "Дніпро", name_en: "Dnipro", color: "red", sequence: 122)
MetroStation.create(district_id: 10, name_ru: "Гидропарк", name_uk: "Гідропарк", name_en: "Hidropark", color: "red", sequence: 123)
MetroStation.create(district_id: 10, name_ru: "Левобережная", name_uk: "Лівобережна", name_en: "Livoberezhna", color: "red", sequence: 124)
MetroStation.create(district_id: 10, name_ru: "Дарница", name_uk: "Дарниця", name_en: "Darnytsia", color: "red", sequence: 125)
MetroStation.create(district_id: 10, name_ru: "Черниговская", name_uk: "Чернігівська", name_en: "Chernihivska", color: "red", sequence: 126)
MetroStation.create(district_id: 10, name_ru: "Лесная", name_uk: "Лісова", name_en: "Lisova", color: "red", sequence: 127)
MetroStation.create(district_id: 10, name_ru: "Героев Днепра", name_uk: "Героїв Дніпра", name_en: "Heroiv Dnipra", color: "blue", sequence: 210)
MetroStation.create(district_id: 10, name_ru: "Минская", name_uk: "Мінська", name_en: "Minska", color: "blue", sequence: 211)
MetroStation.create(district_id: 10, name_ru: "Оболонь", name_uk: "Оболонь", name_en: "Obolon", color: "blue", sequence: 212)
MetroStation.create(district_id: 10, name_ru: "Петровка", name_uk: "Петрівка", name_en: "Petrivka", color: "blue", sequence: 213)
MetroStation.create(district_id: 10, name_ru: "Тараса Шевченко", name_uk: "Тараса Шевченка", name_en: "Tarasa Shevchenka", color: "blue", sequence: 214)
MetroStation.create(district_id: 10, name_ru: "Контрактовая площадь", name_uk: "Контрактова площа", name_en: "Kontraktova Ploshcha", color: "blue", sequence: 215)
MetroStation.create(district_id: 10, name_ru: "Почтовая площадь", name_uk: "Поштова площа", name_en: "Poshtova Ploshcha", color: "blue", sequence: 216)
MetroStation.create(district_id: 10, name_ru: "Площадь Независимости", name_uk: "Майдан Незалежності", name_en: "Maidan Nezalezhnosti", color: "blue", sequence: 217)
MetroStation.create(district_id: 10, name_ru: "Площадь Льва Толстого", name_uk: "Площа Льва Толстого", name_en: "Ploshcha Lva Tolstogo", color: "blue", sequence: 218)
MetroStation.create(district_id: 10, name_ru: "Олимпийская", name_uk: "Олімпійська", name_en: "Olimpiiska", color: "blue", sequence: 219)
MetroStation.create(district_id: 10, name_ru: "Дворец «Украина»", name_uk: "Палац «Україна»", name_en: "Palats «Ukraina»", color: "blue", sequence: 220)
MetroStation.create(district_id: 10, name_ru: "Лыбедская", name_uk: "Либідська", name_en: "Lybidska", color: "blue", sequence: 221)
MetroStation.create(district_id: 10, name_ru: "Демиевская", name_uk: "Деміївська", name_en: "Demiivska", color: "blue", sequence: 222)
MetroStation.create(district_id: 10, name_ru: "Голосеевская", name_uk: "Голосіївська", name_en: "Holosiivska", color: "blue", sequence: 223)
MetroStation.create(district_id: 10, name_ru: "Васильковская", name_uk: "Васильківська", name_en: "Vasylkivska", color: "blue", sequence: 224)
MetroStation.create(district_id: 10, name_ru: "Выставочный центр", name_uk: "Виставковий центр", name_en: "Vystavkovyi Tsentr", color: "blue", sequence: 225)
MetroStation.create(district_id: 10, name_ru: "Ипподром", name_uk: "Іподром", name_en: "Ipodrom", color: "blue", sequence: 226)
MetroStation.create(district_id: 10, name_ru: "Теремки", name_uk: "Теремки", name_en: "Teremky", color: "blue", sequence: 227)
MetroStation.create(district_id: 10, name_ru: "Сырец", name_uk: "Сирець", name_en: "Syrets", color: "green", sequence: 310)
MetroStation.create(district_id: 10, name_ru: "Дорогожичи", name_uk: "Дорогожичі", name_en: "Dorogozhychi", color: "green", sequence: 311)
MetroStation.create(district_id: 10, name_ru: "Лукьяновская", name_uk: "Лук'янівська", name_en: "Lukianivska", color: "green", sequence: 312)
MetroStation.create(district_id: 10, name_ru: "Золотые ворота", name_uk: "Золоті ворота", name_en: "Zoloti Vorota", color: "green", sequence: 314)
MetroStation.create(district_id: 10, name_ru: "Дворец спорта", name_uk: "Палац спорту", name_en: "Palats Sportu", color: "green", sequence: 315)
MetroStation.create(district_id: 10, name_ru: "Кловская", name_uk: "Кловська", name_en: "Klovska", color: "green", sequence: 316)
MetroStation.create(district_id: 10, name_ru: "Печерская", name_uk: "Печерська", name_en: "Pecherska", color: "green", sequence: 317)
MetroStation.create(district_id: 10, name_ru: "Дружбы народов", name_uk: "Дружби народів", name_en: "Druzhby Narodiv", color: "green", sequence: 318)
MetroStation.create(district_id: 10, name_ru: "Выдубичи", name_uk: "Видубичі", name_en: "Vydubychi", color: "green", sequence: 319)
MetroStation.create(district_id: 10, name_ru: "Славутич", name_uk: "Славутич", name_en: "Slavutych", color: "green", sequence: 321)
MetroStation.create(district_id: 10, name_ru: "Осокорки", name_uk: "Осокорки", name_en: "Osokorky", color: "green", sequence: 322)
MetroStation.create(district_id: 10, name_ru: "Позняки", name_uk: "Позняки", name_en: "Pozniaky", color: "green", sequence: 323)
MetroStation.create(district_id: 10, name_ru: "Харьковская", name_uk: "Харківська", name_en: "Kharkivska", color: "green", sequence: 324)
MetroStation.create(district_id: 10, name_ru: "Вырлица", name_uk: "Вирлиця", name_en: "Vyrlytsya", color: "green", sequence: 325)
MetroStation.create(district_id: 10, name_ru: "Бориспольская", name_uk: "Бориспільська", name_en: "Boryspilska", color: "green", sequence: 326)
MetroStation.create(district_id: 10, name_ru: "Красный хутор", name_uk: "Червоний хутір", name_en: "Chervonyi Khutir", color: "green", sequence: 327)

# Kharkiv
MetroStation.create(district_id: 7, name_ru: "Холодная гора", name_uk: "Холодна гора", color: "red", sequence: 110)
MetroStation.create(district_id: 7, name_ru: "Южный вокзал", name_uk: "Південний вокзал", color: "red", sequence: 111)
MetroStation.create(district_id: 7, name_ru: "Центральный рынок", name_uk: "Центральний ринок", color: "red", sequence: 112)
MetroStation.create(district_id: 7, name_ru: "Площадь Конституции", name_uk: "Майдан Конституції", color: "red", sequence: 113)
MetroStation.create(district_id: 7, name_ru: "Проспект Гагарина", name_uk: "Проспект Гагаріна", color: "red", sequence: 114)
MetroStation.create(district_id: 7, name_ru: "Спортивная", name_uk: "Спортивна", color: "red", sequence: 115)
MetroStation.create(district_id: 7, name_ru: "Завод имени Малышева", name_uk: "Завод імені Малишева", color: "red", sequence: 116)
MetroStation.create(district_id: 7, name_ru: "Московский проспект", name_uk: "Московський проспект", color: "red", sequence: 117)
MetroStation.create(district_id: 7, name_ru: "Имени маршала Жукова", name_uk: "Імені маршала Жукова", color: "red", sequence: 118)
MetroStation.create(district_id: 7, name_ru: "Советской армии", name_uk: "Радянської армії", color: "red", sequence: 119)
MetroStation.create(district_id: 7, name_ru: "Имени А. С. Масельского", name_uk: "Імені О. С. Масельського", color: "red", sequence: 120)
MetroStation.create(district_id: 7, name_ru: "Тракторный завод", name_uk: "Тракторний завод", color: "red", sequence: 121)
MetroStation.create(district_id: 7, name_ru: "Пролетарская", name_uk: "Пролетарська", color: "red", sequence: 122)
MetroStation.create(district_id: 7, name_ru: "Героев труда", name_uk: "Героїв праці", color: "blue", sequence: 210)
MetroStation.create(district_id: 7, name_ru: "Студенческая", name_uk: "Студентська", color: "blue", sequence: 211)
MetroStation.create(district_id: 7, name_ru: "Академика Павлова", name_uk: "Академіка Павлова", color: "blue", sequence: 212)
MetroStation.create(district_id: 7, name_ru: "Академика Барабашова", name_uk: "Академіка Барабашова", color: "blue", sequence: 213)
MetroStation.create(district_id: 7, name_ru: "Киевская", name_uk: "Київська", color: "blue", sequence: 214)
MetroStation.create(district_id: 7, name_ru: "Пушкинская", name_uk: "Пушкінська", color: "blue", sequence: 215)
MetroStation.create(district_id: 7, name_ru: "Университет", name_uk: "Університет", color: "blue", sequence: 216)
MetroStation.create(district_id: 7, name_ru: "Исторический музей", name_uk: "Історичний музей", color: "blue", sequence: 217)
MetroStation.create(district_id: 7, name_ru: "Алексеевская", name_uk: "Олексіївська", color: "green", sequence: 310)
MetroStation.create(district_id: 7, name_ru: "23 Августа", name_uk: "23 Серпня", color: "green", sequence: 311)
MetroStation.create(district_id: 7, name_ru: "Ботанический сад", name_uk: "Ботанічний сад", color: "green", sequence: 312)
MetroStation.create(district_id: 7, name_ru: "Научная", name_uk: "Наукова", color: "green", sequence: 313)
MetroStation.create(district_id: 7, name_ru: "Госпром", name_uk: "Держпром", color: "green", sequence: 314)
MetroStation.create(district_id: 7, name_ru: "Архитектора Бекетова", name_uk: "Архітектора Бекетова", color: "green", sequence: 315)
MetroStation.create(district_id: 7, name_ru: "Площадь Восстания", name_uk: "Площа Повстання", color: "green", sequence: 316)
MetroStation.create(district_id: 7, name_ru: "Метростроителей имени Ващенко", name_uk: "Метробудівників імені Ващенка", color: "green", sequence: 317)

# Dnipropetrovsk
MetroStation.create(district_id: 11, name_uk: "Комунарівська", name_ru: "Коммунаровская", color: "red", sequence: 1)
MetroStation.create(district_id: 11, name_uk: "Проспект Свободи", name_ru: "Проспект Свободы", color: "red", sequence: 2)
MetroStation.create(district_id: 11, name_uk: "Заводська", name_ru: "Заводская", color: "red", sequence: 3)
MetroStation.create(district_id: 11, name_uk: "Металургів", name_ru: "Металлургов", color: "red", sequence: 4)
MetroStation.create(district_id: 11, name_uk: "Метробудівників", name_ru: "Метростроителей", color: "red", sequence: 5)
MetroStation.create(district_id: 11, name_uk: "Вокзальна", name_ru: "Вокзальная", color: "red", sequence: 6)
