language: ruby
rvm:
  - 2.0.0
services:
  - mysql
before_script:
  - mysql -e 'create database offers_test;'
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
