default: &default
  adapter: mysql2
  encoding: utf8
  username: root

development:
  <<: *default
  database: offers_development
  pool: 5

test:
  <<: *default
  database: offers_test

staging:
  <<: *default
  database: offers_staging
  username: offers
  password: <%= ENV['OFFERS_DATABASE_PASSWORD'] %>
  pool: 5

production:
  <<: *default
  database: offers_production
  username: offers
  password: <%= ENV['OFFERS_DATABASE_PASSWORD'] %>
  pool: 5
