---
en:
  uk:
    Politics: "Політика"
    Economics: "Економіка"
    Society: "Суспільство"
    Culture: "Культура"
    World: "Світ"
uk:
  ru:
    "Політика": "Политика"
    "Економіка": "Экономика"
    "Суспільство": "Общество"
    "Культура": "Культура"
    "Світ": "Мир"
  en:
    "Політика": "Politics"
    "Економіка": "Economics"
    "Суспільство": "Society"
    "Культура": "Culture"
    "Світ": "World"
